### ISSUE TITLE
cannot connect to database

### ISSUE THREAD

**Issue by tymastrangelo** [tmastrangelo/TwitterBackend#1]
✖ Introspecting based on datasource defined in prisma/schema.prisma

Error: Error: P1001

Can't reach database server at `twitter.cbsq80uyk77o.us-east-1.rds.amazonaws.com`:`5432`

Please make sure your database server is running at `twitter.cbsq80uyk77o.us-east-1.rds.amazonaws.com`:`5432`.

    at Object.<anonymous> (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/prisma/build/index.js:514:8)
    at Ho.handleResponse (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/prisma/build/index.js:506:2821)
    at ll.<anonymous> (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/prisma/build/index.js:510:490)
    at ll.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
    at ll._pushBuffer (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/prisma/build/index.js:500:369)
    at ll._transform (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/prisma/build/index.js:500:199)
    at Transform._write (node:internal/streams/transform:175:8)

**Comment by tymastrangelo** [comment]
my fix. may not work for all instances.

AWS Console -> VPC -> Route Tables -> Edit Routes -> add new route -> destination: 0.0.0.0/0 -> target: igw-xxxxxxx -> save changes
